[tool.ruff]
line-length = 100
target-version = "py312"
exclude = [".git", ".ruff_cache", "__pycache__", "venv", "env", ".env"]

[tool.ruff.lint]
select = ["E", "F", "B", "I", "C90", "W"]
ignore = []
fixable = ["ALL"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --tb=short"
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::UserWarning",
]

[tool.coverage.run]
source = ["."]
omit = ["tests/*", "setup.py"]
