# YOLOv11 segment prediction configuration
# See README.md for details

# Required
model: yolo11l-seg.pt  # Example segmentation model, can be changed
source: /home/wmu/vibe/hub/datasets/VOC/images/test2007
project: runs/predict/segment

# Optional parameters
random_select: 10  # Number of images to randomly select if source is a directory
conf: 0.25  # Confidence threshold
iou: 0.7  # IoU threshold for NMS
imgsz: 640  # Inference size (pixels)
max_det: 300  # Maximum detections per image
device: ''  # cuda device, i.e. 0 or 0,1,2,3 or cpu
save: True  # Save results
save_txt: True  # Save results in .txt format
save_conf: True  # Save confidences in --save-txt labels
retina_masks: True  # Use high-quality segmentation masks
overlap_mask: True  # Allow masks to overlap