# PASCAL VOC 2012 dataset configuration for YOLOv11 Segmentation
# Following project structure defined in docs/dataset/voc/README.md
# Uses images from images/ and expects labels in ../labels_segment/

# Dataset root directory (contains images/, labels_segment/, etc.)
path: /home/ubuntu/vibe/hub/datasets/VOC/segment

# Image directories relative to 'path'
# Using combined 07+12 train/val for training, 07 test for val/test
train:
  - images/train2007
val: images/val2007
test: images/test2007 # Using test2007 set for testing

# Classes (Standard VOC 20 classes)
# Ensure this matches the class indices used during label generation
names:
  0: aeroplane
  1: bicycle
  2: bird
  3: boat
  4: bottle
  5: bus
  6: car
  7: cat
  8: chair
  9: cow
  10: diningtable
  11: dog
  12: horse
  13: motorbike
  14: person
  15: pottedplant
  16: sheep
  17: sofa
  18: train
  19: tvmonitor