# PASCAL VOC Dataset Detection Configuration
# For use with train_detect.py
# NOTE: Requires absolute path for the 'path' key.
# Ensure this path is correct for your environment.

path: /home/ubuntu/vibe/hub/datasets/VOC/detect # Absolute path to VOC dataset base directory

# Train/val/test sets relative to 'path' above
# Using 2007 train/val + 2012 train/val for training
# Using 2007 test for validation and testing
train: # List of directories relative to dataset base path
  - images/train2007
val: images/val2007    # val images (relative to dataset base path)
test: images/test2007   # test images (optional, relative to dataset base path)

# Classes
names:
  0: aeroplane
  1: bicycle
  2: bird
  3: boat
  4: bottle
  5: bus
  6: car
  7: cat
  8: chair
  9: cow
  10: diningtable
  11: dog
  12: horse
  13: motorbike
  14: person
  15: pottedplant
  16: sheep
  17: sofa
  18: train
  19: tvmonitor