# PASCAL VOC 2007 dataset configuration for YOLOv8
# Using pre-split image directories under the specified absolute path

# Dataset root (Ultralytics prepends this to relative paths below)
path: /home/wmu/vibe/hub/datasets/VOC # Use absolute path directly

# Image directories relative to 'path' (VOC2007 only)
train: images/train2007
val: images/val2007
test: images/test2007

# Classes
names:
  0: aeroplane
  1: bicycle
  2: bird
  3: boat
  4: bottle
  5: bus
  6: car
  7: cat
  8: chair
  9: cow
  10: diningtable
  11: dog
  12: horse
  13: motorbike
  14: person
  15: pottedplant
  16: sheep
  17: sofa
  18: train
  19: tvmonitor