# Training configuration for YOLOv8 FROM SCRATCH on combined PASCAL VOC

# --- Base Model Architecture & Dataset ---
# Model architecture YAML (NOT a .pt weights file)
model: yolov8l.yaml
# Path to the dataset definition yaml (relative to project root)
data: src/models/ext/yolov8/configs/voc_combined.yaml

# --- Training Hyperparameters ---
# Number of epochs (more needed for scratch training)
epochs: 300
# Training image size
imgsz: 640
# Batch size (-1 for auto-batch calculation, or specify e.g., 16, 32)
# Adjust based on GPU memory. 16 or 32 should work for 2x A5000 with yolov8l
batch: 16
# Number of worker threads for data loading
workers: 8
# Optimizer: 'SGD', 'Adam', 'AdamW', 'NAdam', 'RAdam', 'RMSProp', 'auto'
optimizer: auto
# Initial learning rate (may need tuning for scratch training)
lr0: 0.01
# Final learning rate (lr0 * lrf)
lrf: 0.01
# Close mosaic augmentation for the last N epochs (set to 0 to disable)
close_mosaic: 10
# Consider using cosine LR schedule for long training runs
# cos_lr: True
# Patience for early stopping (default 100)
# patience: 100
# Add other hyperparameters as needed

# --- Execution Settings ---
# Device: '' for auto, 'cpu', '0', '0,1'
device: '0,1'
# Pretrained: MUST be False for training from scratch
pretrained: False

# --- Output Settings ---
# Default project directory (relative to project root, can be overridden by --project CLI arg)
project: runs/detect

# --- Wandb Logging (will be used automatically if logged in) ---
# Set to False to disable wandb even if installed/logged in
# enable_wandb: True