# Training configuration for fine-tuning YOLOv11 SEGMENTATION on COV_SEGM dataset

# --- Base Model & Dataset ---
# Base model weights file (YOLOv11 Large Segmentation)
model: yolo11l-seg.pt
# Path to the dataset definition yaml (relative to project root)
data: configs/yolov11/cov_segm_segment_visible.yaml

# --- Training Hyperparameters ---
# Number of epochs (increased to compensate for dataset subsampling with fraction)
epochs: 50
# Training image size
imgsz: 640
# Batch size (slightly increased to reduce iterations, while cautious of OOM on T4 GPUs)
# Adjust based on GPU memory (e.g., 12 means 3 per GPU with 4 GPUs)
batch: 64
# Number of worker threads for data loading (increased for large dataset)
workers: 32
# Optimizer: 'SGD', 'Adam', 'AdamW', 'NAdam', 'RAdam', 'RMSProp', 'auto'
# Explicitly set to SGD to use the specified lr0
optimizer: SGD
# Initial learning rate (e.g., 0.01 for SGD, 0.001 for AdamW)
# Suitable for batch=12 on 4 GPUs
lr0: 0.01
# Final learning rate (lr0 * lrf)
lrf: 0.01
# Close mosaic augmentation for the last N epochs (e.g., 10, or 0 to disable)
close_mosaic: 10
# Fraction of dataset to use for training (e.g., 0.1 means use 10% of training data per epoch)
# Added to reduce training time per epoch for very large datasets
fraction: 0.4
# Add other hyperparameters from YOLOv11 docs as needed
# e.g., weight_decay, momentum, warmup_epochs, augmentations (hsv_h, etc.)
# patience: 100

# --- Execution Settings ---
# Device: '' for auto, 'cpu', '0', '0,1'
# Set for 4 T4 GPUs
device: '0,1,2,3'
# Pretrained weights (MUST be True for fine-tuning)
pretrained: True
# Allow overwriting/appending to existing run directory when resuming
exist_ok: True

# --- Output Settings ---
# Default project directory (relative to project root, can be overridden by --project CLI arg)
project: runs/finetune/segment_cov_segm

# --- Wandb Logging (will be used automatically if logged in) ---
# Set to False to disable wandb even if installed/logged in
enable_wandb: True