# Training configuration optimized for 8x A10G GPUs fine-tuning YOLOv11 SEGMENTATION
# on FULL COV_SEGM dataset, with strong regularization to combat overfitting.

# --- Base Model & Dataset ---
model: yolo11l-seg.pt  # Base model weights file (YOLOv11 Large Segmentation)
data: configs/yolov11/cov_segm_segment_full.yaml # Path to the dataset definition yaml.
                      # !! IMPORTANT: Ensure this points to FULL train (216k) & val (10k) sets !!

# --- Training Hyperparameters ---
epochs: 50            # Maximum number of epochs. Early stopping (patience) will likely stop it earlier.
imgsz: 640            # Training image size.
batch: 192             # Batch size for 8x A10G (24GB VRAM). 192 = 24 images/GPU.
                      # Monitor VRAM: if usage < ~22GB, consider increasing to 256 (32/GPU).
workers: 64           # Number of dataloader workers (e.g., 8 per GPU). Adjust based on CPU/IO.
optimizer: SGD        # Optimizer choice. AdamW with lr0=0.0005 could be an alternative.
lr0: 0.01             # Initial learning rate for SGD. Kept relatively low due to strong regularization.
lrf: 0.01             # Final learning rate factor (final_lr = lr0 * lrf).
cos_lr: True          # Use cosine learning rate annealing schedule (Recommended).
fraction: 1.0         # Use 100% of the training dataset per epoch (Essential).
close_mosaic: 10      # Disable mosaic augmentation for the last N epochs (Standard practice).

# --- Regularization & Augmentation to Prevent Overfitting ---
mixup: 0.1            # Enable MixUp augmentation (Helps regularization). Adjust value (0.05-0.15) if needed.
copy_paste: 0.1       # Enable Copy-Paste augmentation (Helps segmentation regularization). Adjust if needed.
dropout: 0.1          # Add dropout for regularization. Check model structure compatibility if issues arise.
weight_decay: 0.0005  # Explicitly set weight decay for SGD.
patience: 30          # Enable early stopping. Stop if val mAP50-95 doesn't improve for 30 epochs.
# Other augmentation defaults from Ultralytics are usually active (e.g., hsv, flip).
# You can tune them further if needed (e.g., scale, translate).

# --- Execution Settings ---
device: '0,1,2,3,4,5,6,7' # Use all 4 A10G GPUs.
pretrained: True      # Start from pretrained weights (Fine-tuning).
exist_ok: True        # Allow overwriting/appending to existing run when resuming (though resume=False here).
amp: True             # Enable Automatic Mixed Precision (Recommended for A10G). Should be default.

# --- Output Settings ---
project: yolo_ultralytics
save_period: 5

# --- Wandb Logging ---
enable_wandb: True    # Set to True to use WandB (ensure you are logged in).