# YOLOv11 detection prediction configuration
# See README.md for details

# Required
model: yolo11l.pt  # Base detection model
# source: removed, will be constructed from --dataset/--tag args

# Output control
project: runs/predict/detect  # Root directory for results
# name: removed, will be provided via --name argument

# Optional prediction parameters
conf: 0.25  # Confidence threshold
iou: 0.7  # IoU threshold for NMS
imgsz: 640  # Inference size (pixels)
max_det: 300  # Maximum detections per image
device: '0'  # cuda device, i.e. 0 or 0,1,2,3 or cpu
save: True  # Save results (images with overlays)
save_txt: True  # Save results in .txt format (YOLO label format)
save_conf: True  # Save confidences in --save-txt labels
save_crop: False  # Save cropped detection images
show: False  # Show results in a window
exist_ok: True  # Allow overwriting existing timestamped folder
classes: null  # Filter results by class, e.g. [0, 1, 5]
agnostic_nms: True  # Use class-agnostic NMS